### ISSUE TITLE
Add some type of typescript check for stories

### ISSUE THREAD

**Issue by essential-randomness** [BobaBoard/boba-components#73]
We're currently in a situation where storybook stories are using outdated or non-existing props of the components they represent. This could have been mitigated by running typescript checks when building/developing storybook (that is, having some way to surface typescript compilation errors of stories somewhere we can see them).

### Tasks

- [ ] Research how to run typescript checks for all the defined stories
- [ ] Decide whether to prevent building storybook (that is, blocking deployment) or e.g. failing an integration test
- [ ] Implement whatever we decide
